#!/usr/bin/env php
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <!-- Meta tags -->
    <meta charset="UTF-8">
    <!-- Favicon and PWA -->
    <link rel="apple-touch-icon" sizes="57x57" href="assets/favicon/apple-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="assets/favicon/apple-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="assets/favicon/apple-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="assets/favicon/apple-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="assets/favicon/apple-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="assets/favicon/apple-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="assets/favicon/apple-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="assets/favicon/apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="assets/favicon/apple-icon-180x180.png">
    <link rel="icon" type="image/png" sizes="192x192" href="assets/favicon/android-icon-192x192.png">
    <link rel="icon" type="image/png" sizes="32x32" href="assets/favicon/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="assets/favicon/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="assets/favicon/favicon-16x16.png">
    <link rel="manifest" href="assets/favicon/manifest.json">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="favicon/ms-icon-144x144.png">
    <meta name="theme-color" content="#ffffff">
    <!-- Facebook Open Graph -->
    <meta property="fb:app_id" content="2052011761683343"/>
    <meta property="og:title" content="Infocorp Developer Team"/>
    <meta property="og:description" content="Time de desenvolvimento da Infocorp"/>
    <meta property="og:url" content="https://dev.infocorpjr.com/"/>
    <meta property="og:type" content="Website"/>
    <meta property="og:image" content="https://dev.infocorpjr.com/assets/favicon/icon-200x200.png"/>
    <!-- The title -->
    <title>Infocorp Developer Team</title>
    <!-- Meta tag's -->
    <meta http-equiv="content-language" content="pt-br">
    <meta http-equiv="content-type" content="text/html; utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Time de desenvolvimento da Infocorp">
    <META name="keywords" content="web, desenvolvimento, site, infocorp, desenvolvedores">
    <meta name="author" content="Jorge Rodrigues"/>
    <meta name="reply-to" content="jorgerodrigues9@outlook.com">
    <!-- Styles -->
    <link href="assets/css/styles.css" rel="stylesheet">
    <!-- Scripts -->
    <script src="assets/js/before.js"></script>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-121056174-1"></script>
    <script>
        window.dataLayer = window.dataLayer || [];

        function gtag() {
            dataLayer.push(arguments);
        }

        gtag('js', new Date());
        gtag('config', 'UA-121056174-1');
    </script>
</head>
<body>
<!-- Featured | BEM CSS PATTERN -->
<div id="featured" class="pbox pfeatured">
    <!-- Mouse -->
    <div class="xtop"></div>
    <div class="yleft"></div>
    <!-- End mouse -->
    <div class="pbox__middle">
        <div class="pbox__middle--content">
            <div class="pfeatured__box">
                <svg class="pfeatured__box--brand" xmlns="http://www.w3.org/2000/svg" xml:space="preserve"
                     viewBox="0 0 200 49" version="1.1" y="0px" x="0px">
                    <g transform="matrix(.18686 0 0 .18681 -31.206 -47.954)">
                        <rect class="st0" height="147" width="37" y="318" x="167"/>
                        <path class="st0"
                              d="m315.9 315c-7 0-13.8 1.4-20.5 4.1-6.7 2.8-14.2 7.6-22.4 14.7v-15.8h-37v147h37v-58.1c0-15.1 0.5-24.9 1.5-29.4 2-8.7 5.6-15.4 10.7-20.4 5.2-4.9 11.3-7.4 18.6-7.4 5.5 0 10.2 1.5 13.9 4.5 3.8 3 6.4 7.3 7.9 12.9 1.5 5.7 2.3 17.2 2.3 34.4v63.5h37v-96.7c0-16.8-4.2-29.5-12.6-38.2-9.9-10.1-22.1-15.1-36.4-15.1z"/>
                        <path class="st0"
                              d="m405.8 263.9c-6 4.8-9.5 11.3-10.5 19.5-0.6 3.6-0.9 15.1-1 34.6h-13.3v32h14v115h36v-115h24v-32h-21l0.1-18.4c0-4.2 0.7-7 2.1-8.4 1.9-1.8 5-2.7 9.2-2.7 3.3 0 7.5 0.8 12.6 2.3v-28.7c-10-3.6-18.9-5.4-26.8-5.4-11 0-19.5 2.4-25.4 7.2z"/>
                        <path class="st0"
                              d="m615 353.6c-6.9-11.7-16.5-21-28.8-27.9s-25.5-10.3-39.5-10.3c-19.4 0-36.5 6.6-51.4 19.7-17 15.2-25.5 34-25.5 56.7 0 21.2 7.5 39.2 22.5 54s33.2 22.2 54.5 22.2c14.4 0 27.7-3.4 39.7-10.1s21.5-16 28.4-28c6.9-11.9 10.4-24.7 10.4-38.4 0.1-13.5-3.4-26.2-10.3-37.9zm-38.3 68c-7.8 7.8-17.6 11.7-29.4 11.7s-21.5-3.9-29.2-11.5c-7.7-7.7-11.5-17.8-11.5-30.2 0-12 3.9-21.9 11.6-29.7 7.7-7.7 17.5-11.6 29.2-11.6 11.9 0 21.7 3.8 29.4 11.5s11.5 17.6 11.5 29.9c0.2 12.1-3.8 22.1-11.6 29.9z"/>
                        <path class="st0"
                              d="m1037.5 320.8c-5.6 3.7-13.5 16.1-13.5 16.1v-18.9h-32v147h37v-58.8l0.5-7.1c0-20.4 1.9-34.1 5.7-41.1s8.4-10.5 13.9-10.5c2.7 0 6.1 1.1 10.3 3.2l11.1-31.6c-5.1-2.5-10-3.8-14.6-3.8-6.8 0-12.9 1.9-18.4 5.5z"/>
                        <path class="st0"
                              d="m1217 336.8c-13.5-14.3-29.9-21.5-49.2-21.5-8.9 0-17.3 1.7-25 5-7.8 3.3-15.1 8.3-21.8 14.9v-17.2h-37v201h37v-70.9c7.2 7.1 14.6 12.2 21.9 15.3 7.4 3.1 15.3 4.7 23.8 4.7 19.1 0 35.7-7.3 49.7-21.8 14-14.6 20.9-32.7 20.9-54.3 0-22.5-6.7-40.8-20.3-55.2zm-28.3 84.7c-7.8 7.9-17.5 11.8-28.9 11.8-11.8 0-21.6-3.9-29.4-11.5-7.8-7.7-11.7-17.8-11.7-30.4 0-12.2 3.9-22.1 11.7-29.8 7.8-7.6 17.6-11.4 29.4-11.4 11.7 0 21.4 3.9 29.1 11.6s11.5 17.6 11.5 29.7c0 12.2-3.9 22.2-11.7 30z"/>
                        <path class="st0"
                              d="m972.1 353.2c-7.2-12.2-17.2-22-30.1-29.1-12.9-7.2-26.6-10.7-41.2-10.7-20.2 0-38.1 6.9-53.7 20.6-2.3 2.1-4.5 4.3-6.6 6.5v-0.1l-75.2 79.7-0.5 0.6c-9.2 11.5-22.1 17.2-38.7 17.2-13.5 0-24.4-4.1-32.6-12.3-8.3-8.2-12.4-18.8-12.4-31.8 0-13.4 4.3-24.3 13-32.9 8.7-8.5 20.1-12.8 34.1-12.8 7.7 0 14.4 1.3 20.2 3.8 5.7 2.5 11.6 7.1 17.4 13.6l31.3-17.5c-7.5-11.1-17.2-19.7-29.1-25.7-11.8-6-25.2-9-40-9-16.1 0-30.6 3.5-43.6 10.6s-23.1 16.8-30.3 29.1c-7.2 12.4-10.8 25.9-10.8 40.5 0 21.2 7.4 39.7 22.2 55.5s35.2 23.7 61.3 23.7c28.9 0 51.3-10.5 67.2-31.4l27.6-32.8c2.9 15.6 10.2 29.3 22.2 41.1 15.7 15.5 34.7 23.2 56.9 23.2 15 0 28.9-3.5 41.4-10.5s22.4-16.7 29.7-29.2c7.2-12.4 10.9-25.8 10.9-40.1 0.2-14.3-3.4-27.5-10.6-39.8zm-39.4 72.2c-8.3 8.4-18.8 12.6-31.3 12.6s-22.9-4.2-31.1-12.5c-8.1-8.3-12.2-19.2-12.2-32.6 0-13 4.1-23.7 12.4-32.1 8.2-8.4 18.6-12.6 31.1-12.6 12.7 0 23.2 4.2 31.3 12.4 8.2 8.3 12.3 19.1 12.3 32.3s-4.2 24-12.5 32.5z"/>
                    </g>
                </svg>
                <h1 class="pfeatured__box--line">
                    Developer team <span class="w">|</span>
                </h1>
            </div>
        </div>
    </div>
    <div class="pbox__bottom">
        <div class="pbox__bottom--content">
            <p class="pfeatured__pdown">
                <a href="#projects" class="pfeatured__pdown--link" title="Veja nossos projetos">
                    <svg class="pfeatured__pdown--icon" xmlns="http://www.w3.org/2000/svg"
                         xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" viewBox="0 0 129 129"
                         enable-background="new 0 0 129 129">
                        <g>
                            <path class="st0"
                                  d="m121.3,34.6c-1.6-1.6-4.2-1.6-5.8,0l-51,51.1-51.1-51.1c-1.6-1.6-4.2-1.6-5.8,0-1.6,1.6-1.6,4.2 0,5.8l53.9,53.9c0.8,0.8 1.8,1.2 2.9,1.2 1,0 2.1-0.4 2.9-1.2l53.9-53.9c1.7-1.6 1.7-4.2 0.1-5.8z"/>
                        </g>
                    </svg>
                </a>
            </p>
        </div>
    </div>
</div>
<!-- Projects | BEM CSS PATTERN -->
<div id="projects" class="pbox pprojects">
    <div class="pbox__top">
        <div class="pbox__top--content">
            <ul class="pnavbar-top">
                <li class="pnavbar-top__up">
                    <a class="pnavbar-top__up--link" href="#featured">
                        <svg class="pnavbar-top__up--icon" version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg"
                             xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
                             viewBox="0 0 489.6 489.6" style="enable-background:new 0 0 489.6 489.6;"
                             xml:space="preserve">
                            <g>
                                <g>
                                    <path d="M244.8,489.6c135,0,244.8-109.8,244.8-244.8S379.8,0,244.8,0S0,109.8,0,244.8
                                    S109.8,489.6,244.8,489.6z M244.8,19.8c124.1,0,225,100.9,225,225s-100.9,225-225,225s-225-100.9-225-225S120.7,19.8,244.8,19.8z"/>
                                    <path class="st0" d="M265.5,326.1c1.9,1.9,4.5,2.9,7,2.9s5.1-1,7-2.9c3.9-3.9,3.9-10.1,0-14l-67.3-67.3l67.3-67.3
                                    c3.9-3.9,3.9-10.1,0-14s-10.1-3.9-14,0l-74.3,74.3c-3.9,3.9-3.9,10.1,0,14L265.5,326.1z"/>
                                </g>
                        </svg>
                    </a>
                </li>
                <li class="pnavbar-top__groups">
                    <p class="pnavbar-top__groups--title">
                        PROJETOS,
                        <span class="pnavbar-top__groups--subtitle">
                            AQUI ESTÃO NOSSOS PROJETOS<br/> EM FASE DE TESTE.
                        </span>
                    </p>
                </li>
            </ul>
        </div>
    </div>
    <div class="pbox__middle">
        <div class="pbox__middle--content">
            <!-- Slider main container -->
            <div id="testing" class="swiper-container swiper__container">
                <!-- Additional required wrapper -->
                <div class="swiper-wrapper swiper__container--wrapper">
                    <!-- Slides -->
                    <?php $a = array_diff(scandir('testing'), array('.', '..', 'backup', 'index.php')); ?>
                    <?php foreach ($a as $b): ?>
                        <div class="swiper-slide swiper__container--slide">
                            <a href="<?php echo "testing/$b" ?>"><?php echo strlen($b) > 13 ? substr($b, 0, 10) . '...' : $b ?></a>
                        </div>
                    <?php endforeach; ?>
                </div>
            </div>
            <!-- If we need pagination -->
            <div id="testing__pagination" class="swiper-pagination swiper__pagination"></div>
        </div>
    </div>
    <div class="pbox__bottom">
        <div class="pbox__bottom--content">
            <ul class="pnavbar-bottom">
                <li class="pnavbar-bottom__groups">
                    <p class="pnavbar-bottom__groups--title">
                        EM FRENTE ...
                        <span class="pnavbar-bottom__groups--subtitle">
                            Quer ver um pouco + ?
                        </span>
                        <span class="w">_</span>
                    </p>
                </li>
                <li class="pnavbar-bottom__down">
                    <a class="pnavbar-bottom__down--link" href="#dev">
                        <svg class="pnavbar-bottom__down--icon" version="1.1" id="Layer_1"
                             xmlns="http://www.w3.org/2000/svg"
                             xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
                             viewBox="0 0 489.6 489.6" style="enable-background:new 0 0 489.6 489.6;"
                             xml:space="preserve">
                            <g>
                                <g>
                                    <path d="M244.8,489.6c135,0,244.8-109.8,244.8-244.8S379.8,0,244.8,0S0,109.8,0,244.8
                                    S109.8,489.6,244.8,489.6z M244.8,19.8c124.1,0,225,100.9,225,225s-100.9,225-225,225s-225-100.9-225-225S120.7,19.8,244.8,19.8z"/>
                                    <path class="st0" d="M265.5,326.1c1.9,1.9,4.5,2.9,7,2.9s5.1-1,7-2.9c3.9-3.9,3.9-10.1,0-14l-67.3-67.3l67.3-67.3
                                    c3.9-3.9,3.9-10.1,0-14s-10.1-3.9-14,0l-74.3,74.3c-3.9,3.9-3.9,10.1,0,14L265.5,326.1z"/>
                                </g>
                        </svg>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</div>
<!-- Dev | BEM CSS PATTERN -->
<div id="dev" class="pbox">
    <div class="pbox__top">
        <div class="pbox__top--content">
            <ul class="pnavbar-top">
                <li class="pnavbar-top__up">
                    <a class="pnavbar-top__up--link" href="#projects">
                        <svg class="pnavbar-top__up--icon" version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg"
                             xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
                             viewBox="0 0 489.6 489.6" style="enable-background:new 0 0 489.6 489.6;"
                             xml:space="preserve">
                            <g>
                                <g>
                                    <path d="M244.8,489.6c135,0,244.8-109.8,244.8-244.8S379.8,0,244.8,0S0,109.8,0,244.8
                                    S109.8,489.6,244.8,489.6z M244.8,19.8c124.1,0,225,100.9,225,225s-100.9,225-225,225s-225-100.9-225-225S120.7,19.8,244.8,19.8z"/>
                                    <path class="st0" d="M265.5,326.1c1.9,1.9,4.5,2.9,7,2.9s5.1-1,7-2.9c3.9-3.9,3.9-10.1,0-14l-67.3-67.3l67.3-67.3
                                    c3.9-3.9,3.9-10.1,0-14s-10.1-3.9-14,0l-74.3,74.3c-3.9,3.9-3.9,10.1,0,14L265.5,326.1z"/>
                                </g>
                        </svg>
                    </a>
                </li>
                <li class="pnavbar-top__groups">
                    <p class="pnavbar-top__groups--title">
                        DESENVOLVIMENTO,
                        <span class="pnavbar-top__groups--subtitle">
                            AQUI ESTÃO NOSSOS PROJETOS<br/> EM DESENVOLVIMENTO.
                        </span>
                    </p>
                </li>
            </ul>
        </div>
    </div>
    <div class="pbox__middle">
        <div class="pbox__middle--content">
            <!-- Slider main container -->
            <div id="developing" class="swiper-container swiper__container">
                <!-- Additional required wrapper -->
                <div class="swiper-wrapper swiper__container--wrapper">
                    <!-- Slides -->
                    <?php $c = array_diff(scandir('developing'), array('.', '..', 'backup', 'index.php')); ?>
                    <?php foreach ($c as $d): ?>
                        <div class="swiper-slide swiper__container--slide">
                            <a href="<?php echo "developing/$d" ?>"><?php echo strlen($d) > 13 ? substr($d, 0, 10) . '...' : $d ?></a>
                        </div>
                    <?php endforeach; ?>
                </div>
            </div>
            <!-- If we need pagination -->
            <div id="developing__pagination" class="swiper-pagination swiper__pagination"></div>
        </div>
    </div>
    <div class="pbox__bottom">
        <div class="pbox__bottom--content">
            <ul class="pnavbar-bottom">
                <li class="pnavbar-bottom__groups">
                    <p class="pnavbar-bottom__groups--title">
                        INFOCORP DEVELOPER TEAM.
                        <span class="pnavbar-bottom__groups--subtitle">
                            Quer saber um pouco + sobre nós?
                        </span>
                        <span class="w">_</span>
                    </p>
                </li>
                <li class="pnavbar-bottom__down">
                    <a class="pnavbar-bottom__down--link" href="#about">
                        <svg class="pnavbar-bottom__down--icon" version="1.1" id="Layer_1"
                             xmlns="http://www.w3.org/2000/svg"
                             xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
                             viewBox="0 0 489.6 489.6" style="enable-background:new 0 0 489.6 489.6;"
                             xml:space="preserve">
                            <g>
                                <g>
                                    <path d="M244.8,489.6c135,0,244.8-109.8,244.8-244.8S379.8,0,244.8,0S0,109.8,0,244.8
                                    S109.8,489.6,244.8,489.6z M244.8,19.8c124.1,0,225,100.9,225,225s-100.9,225-225,225s-225-100.9-225-225S120.7,19.8,244.8,19.8z"/>
                                    <path class="st0" d="M265.5,326.1c1.9,1.9,4.5,2.9,7,2.9s5.1-1,7-2.9c3.9-3.9,3.9-10.1,0-14l-67.3-67.3l67.3-67.3
                                    c3.9-3.9,3.9-10.1,0-14s-10.1-3.9-14,0l-74.3,74.3c-3.9,3.9-3.9,10.1,0,14L265.5,326.1z"/>
                                </g>
                        </svg>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</div>
<!-- About | BEM CSS PATTERN -->
<div id="about" class="pbox pabout">
    <div class="pbox__middle">
        <div class="pbox__middle--content">
            <div class="pbox">
                <div class="pbox__middle">
                    <div class="pbox__middle--content pabout__pbox--left">
                        <div class="pabout__pbox--box">
                            <h1 class="pabout__pbox--title">O TEAM DEV</h1>
                            <p class="pabout__pbox--text">
                                O nosso time é formado por alunos dos cursos de Ciência da Computação e Sistemas de
                                Informação da Universidade Federal de Mato Grosso. O que fazemos? Desenvolvemos sistemas
                                para você e sua empresa. Somos apaixonados pelo que fazemos, no ritmo de sempre aprender
                                e
                                compartilhar conhecimento, além de experiência. O objetivo é simples: aplicar o
                                conhecimento
                                adquirido e mudar a vida das pessoas!
                            </p>
                            <p class="pabout__pbox--links">
                                <a class="pabout__pbox--link" href="#featured">Home</a>
                                <a class="pabout__pbox--link" href="#projects">Teste</a>
                                <a class="pabout__pbox--link" href="#dev">Desenvolvimento</a>
                            </p>
                        </div>
                    </div>
                    <div class="pbox__middle--content pabout__pbox--right"></div>
                </div>
            </div>

        </div>
    </div>
    <div class="pbox__bottom">
        <div class="pbox__bottom--content">
            <p class="pabout__infocorp">
                <b>INFOCORP</b>, Empresa Júnior do Instituto de Computação, UFMT <span class="w">|</span>
            </p>
        </div>
    </div>
</div>
<!-- Default scripts -->
<script src="assets/js/scripts.js"></script>
</body>
</html>